apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-reader
  namespace: task-api
  labels:
    app.kubernetes.io/name: vault-secret-reader
    app.kubernetes.io/part-of: task-api
automountServiceAccountToken: true
