redisOperator:
  webhook: true
  imagePullPolicy: IfNotPresent
  watchNamespace: task-api
  podLabels:
    app: redis-operator
    version: "0.26.0"
    team: platform

replicas: 2

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            name: redis-operator
        topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

rbac:
  enabled: true
  scope: cluster

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
