apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../apps/user-service/base
- ../../../apps/task-service/base
- ../../../apps/comment-service/base
- ../../../apps/search-service/base
- ../../../apps/activity-service/base
- ../../../apps/notification-service/base
- ../../../apps/kong/base
- ../../../apps/pgadmin/base

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: argocd

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: task-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kong-gateway
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
