apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- workload-serviceaccounts.yaml
- human-roles.yaml
- break-glass.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: argocd
