apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: task-api-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
    - task-api
    storageLocation: default
    snapshotVolumes: false
    ttl: 168h0m0s
