global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: user-service
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:8000']

  - job_name: task-service
    metrics_path: /metrics
    static_configs:
      - targets: ['task-service:8000']

  - job_name: comment-service
    metrics_path: /metrics
    static_configs:
      - targets: ['comment-service:8000']

  - job_name: search-service
    metrics_path: /metrics
    static_configs:
      - targets: ['search-service:8000']

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: elasticsearch
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: postgres-user
    static_configs:
      - targets: ['postgres-exporter-user:9187']

  - job_name: postgres-task
    static_configs:
      - targets: ['postgres-exporter-task:9187']

  - job_name: postgres-comment
    static_configs:
      - targets: ['postgres-exporter-comment:9187']

  - job_name: node-exporter
    static_configs:
      - targets: ['host.docker.internal:9100']
