apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kibana-encryption-keys
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: kibana-encryption-keys
    creationPolicy: Owner
  data:
  - secretKey: securityEncryptionKey
    remoteRef:
      key: kibana/encryption-keys
      property: securityEncryptionKey
  - secretKey: savedObjectsEncryptionKey
    remoteRef:
      key: kibana/encryption-keys
      property: savedObjectsEncryptionKey
  - secretKey: reportingEncryptionKey
    remoteRef:
      key: kibana/encryption-keys
      property: reportingEncryptionKey
