apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- vault-secretstore.yaml
- task-service-secrets.yaml
- kibana-secrets.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: argocd
