apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-platform
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: task-api
          serviceAccountRef:
            name: vault-secret-reader
            namespace: task-api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-exporter-credentials
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-platform
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: platform/shared
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: platform/shared
      property: POSTGRES_PASSWORD
  - secretKey: TASK_POSTGRES_USER
    remoteRef:
      key: task-service/db
      property: username
  - secretKey: TASK_POSTGRES_PASSWORD
    remoteRef:
      key: task-service/db
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-exporter-credentials
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-platform
    kind: ClusterSecretStore
  target:
    name: redis-exporter-credentials
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: platform/shared
      property: REDIS_PASSWORD
