apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-shared-credentials
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: platform/shared
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: platform/shared
      property: POSTGRES_PASSWORD
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: platform/shared
      property: REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: pgadmin
    creationPolicy: Owner
  data:
  - secretKey: PGADMIN_DEFAULT_EMAIL
    remoteRef:
      key: pgadmin/config
      property: PGADMIN_DEFAULT_EMAIL
  - secretKey: PGADMIN_DEFAULT_PASSWORD
    remoteRef:
      key: pgadmin/config
      property: PGADMIN_DEFAULT_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-db-app-credentials
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: task-db-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: task-service/db
      property: username
  - secretKey: password
    remoteRef:
      key: task-service/db
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-db-backup-credentials
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: task-db-backup-s3
    creationPolicy: Owner
  data:
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: task-db/backup
      property: ACCESS_KEY_ID
  - secretKey: ACCESS_SECRET_KEY
    remoteRef:
      key: task-db/backup
      property: ACCESS_SECRET_KEY
