apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-task-api
  namespace: task-api
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: task-api
          serviceAccountRef:
            name: vault-secret-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-api-config
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: task-api-config
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: task-api/config
      property: username
  - secretKey: password
    remoteRef:
      key: task-api/config
      property: password
