apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-service-db
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: task-service-db-from-vault
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: task-service/db
      property: username
  - secretKey: password
    remoteRef:
      key: task-service/db
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-service-redis
  namespace: task-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-task-api
    kind: SecretStore
  target:
    name: task-service-redis-from-vault
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: task-service/redis
      property: REDIS_PASSWORD
