apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v20.2.2
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 2Gi
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  monitoring:
    enabled: false
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 1
      portable: false
      encrypted: false
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 2Gi
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          volumeMode: Block
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  cephConfig:
    global:
      osd_pool_default_size: "1"
      mon_warn_on_pool_no_redundancy: "false"
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
      osd:
        interval: 60s
      status:
        interval: 60s
  disruptionManagement:
    managePodBudgets: false
