apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-platform-alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    release: prometheus
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: local-dev-null
      group_by: ["namespace", "service", "alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
      - matchers:
        - severity = "page"
        receiver: local-dev-null
        repeat_interval: 30m
      - matchers:
        - severity = "ticket"
        receiver: local-dev-null
        repeat_interval: 2h
      - matchers:
        - severity = "dashboard"
        receiver: local-dev-null
        repeat_interval: 12h

    receivers:
    - name: local-dev-null

    inhibit_rules:
    - source_matchers:
      - severity = "page"
      target_matchers:
      - severity =~ "ticket|dashboard"
      equal: ["namespace", "service"]
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: platform-alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    release: prometheus
spec:
  replicas: 1
  configSecret: alertmanager-platform-alertmanager
  alertmanagerConfigSelector: {}
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  securityContext:
    fsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    release: prometheus
spec:
  type: ClusterIP
  selector:
    alertmanager: platform-alertmanager
  ports:
  - name: web
    port: 9093
    targetPort: web
    protocol: TCP
