apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- prometheus-rbac.yaml
- prometheus-managed.yaml
- alertmanager.yaml
- prometheus-rules.yaml
- platform-alert-rules.yaml
- service-monitors.yaml
- grafana-dashboards.yaml
- grafana-deployment.yaml
- kube-state-metrics.yaml
- node-exporter.yaml
- redis-exporter.yaml
- postgres-exporter.yaml
- elasticsearch-exporter.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: argocd
