apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: task-api-platform
  namespace: argocd
spec:
  description: GitOps project for the local task-api platform lab
  sourceRepos:
  - https://github.com/wolfixor/full-microservice-kubernetes-compose.git
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
