"""Create tasks table

Revision ID: 001_create_tasks_table
Revises: 
Create Date: 2024-12-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '001_create_tasks_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Try to create ENUM type - use IF NOT EXISTS to handle existing type
    # PostgreSQL doesn't support CREATE TYPE IF NOT EXISTS directly, so we use exception handling
    connection = op.get_bind()
    
    try:
        op.execute("CREATE TYPE taskstatus AS ENUM ('pending', 'in_progress', 'completed')")
    except Exception as e:
        # Check if error is because type already exists
        if 'already exists' not in str(e).lower() and 'duplicateobject' not in str(e).lower():
            raise e
        # Type already exists, which is fine
        pass
    
    # Now create the table with the ENUM type
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    
    # Drop the ENUM type only if no other tables are using it
    # We'll check if the type is still in use before dropping
    connection = op.get_bind()
    result = connection.execute(
        """SELECT EXISTS (
            SELECT 1 FROM pg_type t 
            JOIN pg_enum e ON t.oid = e.enumtypid 
            WHERE t.typname = 'taskstatus'
        )"""
    ).scalar()
    
    if result:
        op.execute("DROP TYPE IF EXISTS taskstatus")
    # ### end Alembic commands ###