apiVersion: batch/v1
kind: Job
metadata:
  name: comment-service-migrations
  namespace: task-api
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: registry.gitlab.shiveh.com/mapir/upstream/kibana:comment-service
        command: ["/bin/bash", "-c", "alembic upgrade head"]
        env:
        - name: POSTGRES_HOST
          value: "comment-service-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "comment_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
      restartPolicy: Never
  backoffLimit: 3