apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: task-service-success-rate
  namespace: task-api
spec:
  metrics:
  - name: task-service-error-rate
    interval: 30s
    count: 2
    failureLimit: 1
    successCondition: result[0] < 0.05
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc:9090
        query: |
          (
            sum(rate(http_requests_total{service="task-service",status=~"5.*"}[1m]))
            /
            clamp_min(sum(rate(http_requests_total{service="task-service"}[1m])), 1)
          ) or vector(0)
  - name: task-service-p95-latency
    interval: 30s
    count: 2
    failureLimit: 1
    successCondition: result[0] < 0.5
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc:9090
        query: |
          histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket{service="task-service"}[1m])) by (le)
          ) or vector(0)
