apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: task-api-platform
spec:
  project: task-api-platform
  source:
    repoURL: https://github.com/wolfixor/full-microservice-kubernetes-compose.git
    targetRevision: main
    path: k8s/platform/secrets/base
  destination:
    server: https://kubernetes.default.svc
    namespace: task-api
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
