apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: task-api-platform
spec:
  project: task-api-platform
  source:
    repoURL: https://github.com/wolfixor/full-microservice-kubernetes-compose.git
    targetRevision: main
    path: k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
