operators:
  enabled: true
  argocdServerReplicas: 1
  argocdRepoServerReplicas: 1
  argoRolloutsReplicas: 1
  externalSecretsReplicas: 1
  kyvernoAdmissionReplicas: 1
  kyvernoBackgroundReplicas: 1
  kyvernoCleanupReplicas: 1
  kyvernoReportsEnabled: true
  kyvernoReportsReplicas: 1
  kyvernoForceFailurePolicyIgnore: true
  trivyScanJobsConcurrentLimit: 2
