operators:
  enabled: true
  argocdServerReplicas: 2
  argocdRepoServerReplicas: 2
  argoRolloutsReplicas: 2
  externalSecretsReplicas: 2
  kyvernoAdmissionReplicas: 3
  kyvernoBackgroundReplicas: 2
  kyvernoCleanupReplicas: 2
  kyvernoReportsEnabled: true
  kyvernoReportsReplicas: 2
  kyvernoForceFailurePolicyIgnore: false
  trivyScanJobsConcurrentLimit: 10
  kubeStateMetricsImageTag: v2.20.0
