operators:
  enabled: true
  argocdServerReplicas: 2
  argocdRepoServerReplicas: 2
  argoRolloutsReplicas: 2
  externalSecretsReplicas: 2
  kyvernoAdmissionReplicas: 2
  kyvernoBackgroundReplicas: 2
  kyvernoCleanupReplicas: 1
  kyvernoReportsEnabled: true
  kyvernoReportsReplicas: 1
  kyvernoForceFailurePolicyIgnore: false
  trivyScanJobsConcurrentLimit: 5
  kubeStateMetricsImageTag: v2.20.0
