apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-postgres
  namespace: task-api
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - user-service
      - task-service
      - comment-service
      - activity-service
      - notification-service
      - pgadmin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - user-service-db
          - comment-service-db
          - activity-service-db
          - notification-service-db
    - podSelector:
        matchLabels:
          cnpg.io/poolerName: task-db-pooler-rw
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-from-apps
  namespace: task-api
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - user-service-db
      - comment-service-db
      - activity-service-db
      - notification-service-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - user-service
          - task-service
          - comment-service
          - activity-service
          - notification-service
          - pgadmin
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app: postgres-exporter
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-pooler-from-apps
  namespace: task-api
spec:
  podSelector:
    matchLabels:
      cnpg.io/poolerName: task-db-pooler-rw
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - user-service
          - task-service
          - comment-service
          - activity-service
          - notification-service
          - pgadmin
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app: postgres-exporter
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-redis
  namespace: task-api
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - user-service
      - task-service
      - comment-service
      - search-service
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis-cluster
    ports:
    - protocol: TCP
      port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-from-apps
  namespace: task-api
spec:
  podSelector:
    matchLabels:
      app: redis-cluster
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - user-service
          - task-service
          - comment-service
          - search-service
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app: redis-exporter
    ports:
    - protocol: TCP
      port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-kafka
  namespace: task-api
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - user-service
      - task-service
      - comment-service
      - search-service
      - activity-service
      - notification-service
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kafka
    ports:
    - protocol: TCP
      port: 9092
