apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-local-tool-access
  namespace: task-api
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kibana
      - pgadmin
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 5601
    - protocol: TCP
      port: 80
