apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-default-deny-app-workloads.yaml
- 10-allow-dns-egress.yaml
- 20-allow-kong-to-services.yaml
- 30-allow-app-dependencies.yaml
- 40-allow-elasticsearch-and-logging.yaml
- 50-allow-prometheus-scrape.yaml
- 60-allow-local-tool-access.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: argocd
