apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-api-workload
  namespace: task-api
  labels:
    app.kubernetes.io/name: task-api-workload
    app.kubernetes.io/part-of: task-api
automountServiceAccountToken: false
