# apiVersion: v1
# kind: Service
# metadata:
#   name: kong-gateway
#   namespace: task-api
#   labels:
#     app: kong-gateway
# spec:
#   type: LoadBalancer
#   selector:
#     app: kong-gateway
#   ports:
#   - name: proxy
#     port: 80
#     targetPort: 8000
#     protocol: TCP
#   - name: admin
#     port: 8001
#     targetPort: 8001
#     protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
  namespace: task-api
  labels:
    app: kong-gateway
spec:
  type: NodePort
  selector:
    app: kong-gateway
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    nodePort: 30085
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    nodePort: 30086
    protocol: TCP