apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- task-api-pod-security.yaml
- audit-baseline.yaml
- enforce-no-privileged.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: argocd
